image: ubuntu

test:
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - apt-get install -y libsndfile1
    - pip3 install -r requirements.txt
    - python3 -m unittest discover -v -s ./test -p '*test*.py'
